name: UHCPlugin
version: 0.1.0
authors:
  - Rewind
  - Balduvian
  - Varas
  - Sumdumdude
main: com.codeland.uhc.UHCPlugin
api-version: 1.15

commands:
  setup:
    description: Setup the UHC round
    usage: /<command>